version: "3.9"

services:
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shipment-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LateralInterview!1"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - shipment_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P LateralInterview!1 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - shipment-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shipment-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ShipmentDB;User Id=sa;Password=LateralInterview!1;TrustServerCertificate=True;MultipleActiveResultSets=true"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - shipment-network
    restart: on-failure

volumes:
  shipment_sql_data:

networks:
  shipment-network:
    driver: bridge